# Generated by Django 3.1.4 on 2020-12-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensordata',
            table='SENSOR',
        ),
    ]
