# Generated by Django 3.1.4 on 2020-12-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFarm', '0002_auto_20201216_0907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensordata',
        ),
    ]
