# Generated by Django 3.1.4 on 2020-12-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFarm', '0004_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensordata',
            fields=[
                ('sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('humidity', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('moisture', models.IntegerField()),
                ('predicted_crop', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'SENSOR',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
